Ultrasonic_SR04: SR04 Class Reference
SR04 Class Reference
#include <SR04.h>
Public Member Functions
SR04 (int echoPin, int triggerPin)
long Distance ()
long DistanceAvg (int wait=DEFAULT_DELAY, int count=DEFAULT_PINGS)
void Ping ()
long getDistance ()
Private Member Functions
long MicrosecondsToCentimeter (long duration)
Private Attributes
long _currentDistance
int _echoPin
int _triggerPin
long _duration
long _distance
bool _autoMode
Detailed Description
Definition at line 16 of file SR04.h.
Constructor & Destructor Documentation
SR04::SR04 (int echoPin, int triggerPin)
Constructor Ultrasonic sensor SR04, four connections pins VCC, ECHO, TRIGGER, GND
Parameters:
echoPin digital INPUT-Pin for measuring distance
triggerPin if 10us high a trigger signal is generated from SR04
Returns:
void
Definition at line 4 of file SR04.cpp.
References _autoMode, _distance, _echoPin, and _triggerPin.
Member Function Documentation
long SR04::Distance ()
Do a measurment for this sensor. Return distance as long in centimenter
Returns:
long distance in centimeter
Definition at line 14 of file SR04.cpp.
References _duration, _echoPin, _triggerPin, MicrosecondsToCentimeter(), and PULSE_TIMEOUT.
Referenced by DistanceAvg(), and Ping().
long SR04::DistanceAvg (int wait = DEFAULT_DELAY, int count = DEFAULT_PINGS)
Do count measurents and calculate the average. To avoid defilement from ow/high peaks, min/max values are substracted from the average
Parameters:
wait delay between measurements, default = DEFAULT_DELAY/ms
count number of measurements, default DEFAULT_PINGS
Returns:
long distance in centimeter
Definition at line 29 of file SR04.cpp.
References Distance().
void SR04::Ping ()
Do only a ping. Get result with methode getDistance()
Parameters:
keine
Definition at line 64 of file SR04.cpp.
References _distance, and Distance().
long SR04::getDistance ()
return latest distance. Methode Ping() should be called before
Parameters:
keine
Returns:
Distanz in Zentimeter
Definition at line 68 of file SR04.cpp.
References _distance.
long SR04::MicrosecondsToCentimeter (long duration) [private]
Do the measurement calculation and return result in centimeter SR04 measure echo time to obstacle and return way.
Sound travels with 340m/sec
Example: Obstace 100cm away from SR04. Measure time is 100cm to obstacle and 100cm return = 200cm
1sec = 1000ms = 1.000.000uS 1.000.000 / 340 = Distance in microseconds for 100cm 2941uS fuer 100cm = 5882 uS fuer 200cm
duration / 5882 * 100 = distance in cm
Definition at line 72 of file SR04.cpp.
Referenced by Distance().
Member Data Documentation
long SR04::_currentDistance [private]
Definition at line 83 of file SR04.h.
int SR04::_echoPin [private]
Definition at line 84 of file SR04.h.
Referenced by Distance(), and SR04().
int SR04::_triggerPin [private]
Definition at line 84 of file SR04.h.
Referenced by Distance(), and SR04().
long SR04::_duration [private]
Definition at line 85 of file SR04.h.
Referenced by Distance().
long SR04::_distance [private]
Definition at line 85 of file SR04.h.
Referenced by getDistance(), Ping(), and SR04().
bool SR04::_autoMode [private]
Definition at line 86 of file SR04.h.
Referenced by SR04().
The documentation for this class was generated from the following files:
K:/Projekte/robotic/arduino/arduino_1-0Patch/libraries/SR04/SR04.h
K:/Projekte/robotic/arduino/arduino_1-0Patch/libraries/SR04/SR04.cpp